using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Sentrix
{
    public class MT5AutoAttachService
    {
        private readonly string _mt5DataPath;
        private bool _attachAttempted;

        public MT5AutoAttachService(string mt5DataPath)
        {
            _mt5DataPath = mt5DataPath;
        }
        public void EnsureEAAttached(Process mt5Process, string mt5ExePath)
        {
            if (_attachAttempted) return;
            _attachAttempted = true;

            Task.Run(() =>
            {
                try
                {
                    // MT5 is already running — write the attach script
                    WriteAttachScript();
                    Debug.WriteLine("MT5AutoAttach: attach script written.");
                }
                catch (Exception ex)
                {
                    Debug.WriteLine($"MT5AutoAttach error: {ex.Message}");
                }
            });
        }

        // ── Reset so next MT5 launch re-attaches ─────────────────────────
        public void Reset() => _attachAttempted = false;

        // ── Write a MQL5 script that attaches the EA to the first chart ──
        //
        //  MT5 will compile and run this automatically if you place it in
        //  the Scripts folder AND add it to the startup profile.
        //
        private void WriteAttachScript()
        {
            string scriptsFolder = Path.Combine(
                _mt5DataPath, "MQL5", "Scripts", "Sentrix");
            Directory.CreateDirectory(scriptsFolder);

            string scriptPath = Path.Combine(scriptsFolder, "SentriXAutoAttach.mq5");

            // This script runs once, attaches the EA, then removes itself
            File.WriteAllText(scriptPath, @"
                                        //+------------------------------------------------------------------+
                                        //| SentriXAutoAttach.mq5 — one-shot EA attach script                |
                                        //| Auto-generated by Sentrix. Safe to delete after first run.       |
                                        //+------------------------------------------------------------------+
                                        #property script_show_inputs false

                                        void OnStart()
                                        {
                                           long chartId = ChartFirst();
                                           if(chartId < 0)
                                           {
                                              Print('SentriXAutoAttach: no chart found');
                                              return;
                                           }

                                           // Remove EA if already attached (prevents duplicates on reinstall)
                                           ChartExpertDelete(chartId, 0);

                                           // Attach SentriXBridge EA to first chart
                                           if(ChartExpertAttach(chartId, 0, ""Experts\\SentriXBridge"", """"))
                                              Print('SentriXAutoAttach: SentriXBridge attached successfully.');
                                           else
                                              Print('SentriXAutoAttach: attach failed — error ', GetLastError());
                                        }
                                        ");

            // Now tell MT5's default profile to run this script on startup
            AddScriptToStartupProfile(scriptsFolder);
        }

        // ── Add the attach script to MT5's startup profile ────────────────
        private void AddScriptToStartupProfile(string scriptsFolder)
        {
            try
            {
                string profilePath = Path.Combine(
                    _mt5DataPath, "profiles", "default", "chart01.chr");

                if (!File.Exists(profilePath))
                {
                    // Profile doesn't exist yet — the installer's WriteChartProfile
                    // already handles this case with the EA pre-attached directly.
                    return;
                }

                string content = File.ReadAllText(profilePath);

                // Only add if not already present
                if (content.Contains("SentriXBridge")) return;

                // Inject EA section before </chart>
                string injection =
                    "<expert>\r\n" +
                    "name=SentriXBridge\r\n" +
                    "window=0\r\n" +
                    "login=0\r\n" +
                    "symbol=EURUSD\r\n" +
                    "</expert>\r\n";

                content = content.Replace("</chart>", injection + "</chart>");
                File.WriteAllText(profilePath, content);

                Debug.WriteLine("MT5AutoAttach: EA injected into chart profile.");
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"AddScriptToStartupProfile warning: {ex.Message}");
            }
        }

        // ── Find MT5 exe path from running process ────────────────────────
        public static string GetMT5ExePath(Process mt5Process)
        {
            try
            {
                return mt5Process.MainModule?.FileName;
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"GetMT5ExePath warning: {ex.Message}");
                return null;
            }
        }


    }
}
